---- Hana Code
-- ##################################################
-- Procedure: ESPL_LEDGER_REPORT_OPCH
-- Description: This stored procedure generates a detailed ledger report for a specific vendor (CardCode) 
-- within a specified date range (FromDate to ToDate). The report includes transaction details such as balances, 
-- payments, invoices, tax information, and cumulative balances in both local and foreign currencies.
-- ##################################################


ALTER PROCEDURE "ESPL_LEDGER_REPORT_OPCH" 
(
IN CardCode NVARCHAR(100), 
IN FromDate DATE, 
IN ToDate DATE
)

AS
BEGIN
DECLARE i INT DEFAULT 1;
DECLARE SumLocTotalFC DECIMAL;
DECLARE j INT DEFAULT 1;
DECLARE SumLocTotal DECIMAL;
DECLARE continueLoop BOOLEAN DEFAULT TRUE;

CREATE LOCAL TEMPORARY TABLE "#CumulativeBalanceLC" ("LineID" INT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 INCREMENT BY 1), "CBalance" DECIMAL);
CREATE LOCAL TEMPORARY TABLE "#CumulativeBalanceFC" ("LineID" INT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 INCREMENT BY 1), "CBalance" DECIMAL);
CREATE LOCAL TEMPORARY TABLE "#CreditDebitLC" ("LineID" INT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 INCREMENT BY 1), "Balance" DECIMAL);
CREATE LOCAL TEMPORARY TABLE "#CreditDebitFC" ("LineID" INT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 INCREMENT BY 1), "Balance" DECIMAL);


INSERT INTO "#CreditDebitLC" ("Balance")
SELECT "LocTotal" 
FROM "OJDT" "J"
INNER JOIN "OPCH" "O" ON "O"."TransId" = "J"."TransId"
WHERE "O"."CardCode" = :CardCode AND "J"."TransType" = "O"."ObjType" AND "J"."RefDate" >= :FromDate AND "J"."RefDate" <= :ToDate ;
--ORDER BY "J"."RefDate";



SELECT SUM("LocTotal") INTO SumLocTotal
FROM "OJDT" "J"
INNER JOIN "OPCH" "O" ON "O"."TransId" = "J"."TransId"
WHERE "O"."CardCode" = :CardCode AND "J"."TransType" = "O"."ObjType" and "J"."RefDate" < :FromDate;

IF :SumLocTotal IS NOT NULL THEN
    INSERT INTO "#CumulativeBalanceLC" ("CBalance") VALUES (:SumLocTotal);
ELSE
    INSERT INTO "#CumulativeBalanceLC" ("CBalance") VALUES (0);
END IF;


WHILE  :continueLoop = true DO
    INSERT INTO "#CumulativeBalanceLC" ("CBalance")
    VALUES 
        ((SELECT "Balance" FROM "#CreditDebitLC" WHERE "LineID" = :i) + (SELECT "CBalance" FROM "#CumulativeBalanceLC" WHERE "LineID" = :i));
    i := :i + 1;

    IF NOT EXISTS (SELECT "Balance" 
                   FROM "#CreditDebitLC" 
                   WHERE "LineID" = :i) THEN
		continueLoop := FALSE; 
    END IF;
END WHILE;


INSERT INTO "#CreditDebitFC" ("Balance")
SELECT "FcTotal" 
FROM "OJDT" "J"
INNER JOIN "OPCH" "O" ON "O"."TransId" = "J"."TransId"
WHERE "O"."CardCode" = :CardCode AND "J"."TransType" = "O"."ObjType" AND "J"."RefDate" >= :FromDate AND "J"."RefDate" <= :ToDate;
--ORDER BY "J"."RefDate";



SELECT SUM("FcTotal") INTO SumLocTotalFC
FROM "OJDT" "J"
INNER JOIN "OPCH" "O" ON "O"."TransId" = "J"."TransId"
WHERE "O"."CardCode" = :CardCode AND "J"."TransType" = "O"."ObjType" AND "J"."RefDate" < :FromDate;
--ORDER BY "J"."RefDate";

IF :SumLocTotalFC IS NOT NULL THEN
    INSERT INTO "#CumulativeBalanceFC" ("CBalance") VALUES (:SumLocTotalFC);
ELSE
    INSERT INTO "#CumulativeBalanceFC" ("CBalance") VALUES (0);
END IF;


 

WHILE :continueLoop = true DO
    INSERT INTO "#CumulativeBalanceFC" ("CBalance")
   	VALUES ((SELECT "Balance" FROM "#CreditDebitFC" WHERE "LineID" = :j) + 
           (SELECT "CBalance" FROM "#CumulativeBalanceFC" WHERE "LineID" = :j));
    j := :j + 1;
    IF NOT EXISTS (SELECT "Balance" FROM "#CreditDebitFC" WHERE "LineID" = :j) THEN
       	continueLoop := false;
    END IF;
END WHILE;


CREATE LOCAL TEMPORARY TABLE "#ESPL_TBL_LEDGER" (
    "LineID" INT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 INCREMENT BY 1),
    "CompanyName" NVARCHAR(200),
    "CompanyAddress" NVARCHAR(200),
    "PostingDate" DATETIME,
    "TaxDate" DATETIME,
    "InvoiceNo" INT,
    "TotalNoofInvoice" INT,
    "DueBalanceLC" DECIMAL,
    "CrdDbtLC" DECIMAL,
    "CumulativeBalanceLC" DECIMAL,
    "DueBalanceFC" DECIMAL,
    "CrdDbtFC" DECIMAL,
    "CumulativeBalanceFC" DECIMAL,
    "AccountBalanceBP" DECIMAL,
    "GLAccountBPCode" NVARCHAR(200),
    "GLAccountBPName" NVARCHAR(200),
    "GLAccountBPCurrency" NVARCHAR(200),
    "Trans" INT,
    "Details" NVARCHAR(200),
    "OffsetAccount" INT,
    "Origin" NVARCHAR(50)
);


INSERT INTO "#ESPL_TBL_LEDGER" (
    "CompanyName",
    "CompanyAddress",
    "PostingDate",
    "TaxDate",
    "InvoiceNo",
    "TotalNoofInvoice",
    "DueBalanceLC",
    "CrdDbtLC",
    "DueBalanceFC",
    "CrdDbtFC",
    "AccountBalanceBP",
    "GLAccountBPCode",
    "GLAccountBPName",
    "GLAccountBPCurrency",
    "Trans",
    "Details",
    "OffsetAccount",
    "Origin"
)
SELECT
    (SELECT "CompnyName" FROM "OADM") AS "CompanyName",
    (SELECT "CompnyAddr" FROM "OADM") AS "CompanyAddress",
    "J"."RefDate" AS "PostingDate",
    "O"."TaxDate" AS "DocumentDate",
    "J"."BaseRef" AS "InvoiceNo",
    (SELECT COUNT(*) 
     FROM "OJDT" "J" 
     INNER JOIN "OPCH" "O" ON "O"."TransId" = "J"."TransId"
     WHERE "O"."CardCode" = :CardCode AND "J"."TransType" = "O"."ObjType") AS "TotalNoofInvoice",
    (SELECT SUM("BalDueDeb") 
     FROM "JDT1" "A" 
     INNER JOIN "OPCH" "O" ON "O"."TransId" = "A"."TransId"
     WHERE "O"."CardCode" = :CardCode AND "A"."TransType" = "O"."ObjType" AND "A"."TransId" = "J"."TransId") AS "DueBalanceLC",
    (SELECT SUM("Debit") 
     FROM "JDT1" "A" 
     INNER JOIN "OPCH" "O" ON "O"."TransId" = "A"."TransId"
     WHERE "O"."CardCode" = :CardCode AND "A"."TransType" = "O"."ObjType" AND "A"."TransId" = "J"."TransId") AS "CrdDbtLC",
    (SELECT SUM("BalFcDeb") 
     FROM "JDT1" "A" 
     INNER JOIN "OPCH" "O" ON "O"."TransId" = "A"."TransId"
     WHERE "O"."CardCode" = :CardCode AND "A"."TransType" = "O"."ObjType" AND "A"."TransId" = "J"."TransId") AS "DueBalanceFC",
    (SELECT SUM("FCDebit") 
     FROM "JDT1" "A" 
     INNER JOIN "OPCH" "O" ON "O"."TransId" = "A"."TransId"
     WHERE "O"."CardCode" = :CardCode AND "A"."TransType" = "O"."ObjType" AND "A"."TransId" = "J"."TransId") AS "CrdDbtFC",
    "C"."Balance" AS "AccountBalanceBP",
    "C"."CardCode" AS "GLAccountBPCode",
    "C"."CardName" AS "GLAccountBPName",
    "R"."CurrName" AS "GLAccountBPCurrency",
    "J"."TransId" AS "Trans",
    "T"."LineMemo" AS "Details",
    "T"."ContraAct" AS "OffsetAccount",
    'PU' AS "Origin"
FROM "OJDT" "J"
INNER JOIN "JDT1" "T" ON "T"."TransId" = "J"."TransId" AND "T"."BaseRef" = "J"."BaseRef" AND "T"."Line_ID" = 0 
INNER JOIN "OPCH" "O" ON "O"."TransId" = "J"."TransId" AND "O"."ObjType" = "J"."TransType"
INNER JOIN "PCH1" "P" ON "P"."DocEntry" = "O"."DocEntry"
INNER JOIN "OCRD" "C" ON "C"."CardCode" = "O"."CardCode"
INNER JOIN "OCRN" "R" ON "R"."CurrCode" = "C"."Currency"
WHERE "O"."CardCode" = :CardCode AND "J"."TransType" = "O"."ObjType"  AND "J"."RefDate" >= :FromDate AND "J"."RefDate" <= :ToDate;

UPDATE "E"
SET "E"."CumulativeBalanceLC" = "C"."CBalance"
FROM "#ESPL_TBL_LEDGER" "E"
INNER JOIN "#CumulativeBalanceLC" "C" ON "E"."LineID" + 1 = "C"."LineID";


UPDATE "E"
SET "E"."CumulativeBalanceFC" = "C"."CBalance"
FROM "#ESPL_TBL_LEDGER" "E"
INNER JOIN "#CumulativeBalanceFC" "C" ON "E"."LineID" + 1 = "C"."LineID";


SELECT 
    *, 
    (SELECT SUM("CrdDbtLC") FROM "#ESPL_TBL_LEDGER") AS "TotalPaymentMade",
    (SELECT SUM("DueBalanceLC") FROM "#ESPL_TBL_LEDGER") AS "OutstandingBalance"
FROM "#ESPL_TBL_LEDGER" "E";
--order by "PostingDate" asc;


DROP TABLE "#ESPL_TBL_LEDGER";
DROP TABLE "#CreditDebitLC";
DROP TABLE "#CumulativeBalanceLC";
DROP TABLE "#CreditDebitFC";
DROP TABLE "#CumulativeBalanceFC";


END;

CALL ESPL_LEDGER_REPORT_OPCH ('V0044', '2023-04-01', '2024-07-11');

DROP Procedure ESPL_LEDGER_REPORT_OPCH;

SELECT sum(T."Debit" - T."Credit") as "Cumulative"
FROM "OJDT" J
inner JOIN "JDT1" T ON T."TransId" = J."TransId" AND T."BaseRef" = J."BaseRef" and T."Line_ID" = 0
inner JOIN "OPCH" O ON O."TransId" = J."TransId" AND O."ObjType" = J."TransType"
WHERE O."CardCode" = 'V0053' and J."RefDate" < '2023-04-01'  --and J."RefDate" <= '2024-07-11' and T."Line_ID" = 0
;

SELECT T.* 
FROM "OJDT" J
inner JOIN "JDT1" T ON T."TransId" = J."TransId" AND T."BaseRef" = J."BaseRef" and T."Line_ID" = 0
inner JOIN "OPCH" O ON O."TransId" = J."TransId" AND O."ObjType" = J."TransType"
WHERE O."CardCode" = 'V0053' and J."RefDate" < '2023-04-01'  --and J."RefDate" <= '2024-07-11' and T."Line_ID" = 0
;

SELECT * FROM OADM;
SELECT * FROM OJDT;
SELECT * FROM JDT1;
